substitutions:
  name: "living-room-echo-plug"
  friendly_name: "Living Room Echo Plug"
  project_name: "livging-room-echo.smart-plug"
  project_version: "1.0"
  relay_restore_mode: RESTORE_DEFAULT_OFF

packages:
  athom: !include common/athom_resettimer.yaml