substitutions:
  name: "alpha-radiator-plug"
  friendly_name: "Alpha's Radiator Plug"
  project_name: "alpha-radiator.smart-plug"
  project_version: "1.0"
  relay_restore_mode: RESTORE_DEFAULT_ON
  fallbackssid: "Radiator_Fallback"

packages:
  athom: !include common/athom.yaml

sensor: