substitutions:
  name: "ev-plug"
  friendly_name: "EV Plug"
  project_name: "ev-plug.smart-plug"
  project_version: "1.0"
  relay_restore_mode: ALWAYS_ON

esphome:
  name: "${name}"
  name_add_mac_suffix: false

esp8266:
  board: esp8285
  restore_from_flash: true

api:
  password: !secret apipw
  
ota:

logger:

web_server:
  port: 80

wifi:
  ssid: !secret ssid  
  password: !secret wappw
  ap:
    ssid: ${name} fallback AP
    password: !secret hotspotpw  

captive_portal:

dashboard_import:
  package_import_url: github://athom-tech/athom-configs/athom-smart-plug.yaml

binary_sensor:
  - platform: status
    name: "${friendly_name} Status"

status_led:
  pin:
    inverted: True
    number: GPIO13

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO4
    cf1_pin: GPIO5
    voltage_divider: 780
    current:
      name: "${friendly_name} Current"
      filters:
          - calibrate_linear:
            - 0.0000 -> 0.0110 # Relay off no load
            - 0.0097 -> 0.0260 # Relay on no load
            - 0.9270 -> 0.7570
            - 2.0133 -> 1.6330
            - 2.9307 -> 2.3750
            - 5.4848 -> 4.4210
            - 8.4308 -> 6.8330
            - 9.9171 -> 7.9830
          # Normalize for plug load
          - lambda: if (x < 0.0260) return 0; else return (x - 0.0260);
    voltage:
      name: "${friendly_name} Voltage"

    power:
      name: "${friendly_name} Power"
      id: socket_my_power
      unit_of_measurement: W
      filters:
          - calibrate_linear:
            - 0.0000 -> 0.5900 # Relay off no load
            - 0.0000 -> 1.5600 # Relay on no load
            - 198.5129 -> 87.8300
            - 434.2469 -> 189.5000
            - 628.6241 -> 273.9000
            - 1067.0067 -> 460.1000
            - 1619.8098 -> 699.2000
            - 2043.0282 -> 885.0000
          # Normalize for plug load
          - lambda: if (x < 1.5600) return 0; else return (x - 1.5600);
    change_mode_every: 1
    update_interval: 5s

  - platform: total_daily_energy
    name: "${friendly_name} Total Energy"
    power_id: socket_my_power
    unit_of_measurement: kWh
    accuracy_decimals: 3
    restore: true
    min_save_interval: 180s
    filters:
      - multiply: 0.001

switch:
  - platform: gpio
    # name: "${friendly_name}"
    pin: GPIO14
    id: relay
    internal: true
    restore_mode: ${relay_restore_mode}

time:
  - platform: sntp

