substitutions:
  devicename: index-base-rear
  friendlyname: Index VR Rear Base Station Plug
  fallbackssid: VR2 Fallback AP

packages:
  sonoff: !include common/sonoff.yaml

# wifi:
#   use_address: ev-plug.local
