substitutions:
  devicename: "master-bathroom-heater-plug"
  friendlyname: "Master Bathroom Heater Plug"
  project_name: "master-bathroom-heater-plug.smart-plug"
  project_version: "1.0"
  relay_restore_mode: RESTORE_DEFAULT_ON
  fallbackssid: "bathroom-heater-fallback"

packages:
  sonoff: !include common/sonoff_noswitch_binary.yaml

sensor: