esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret ssid  
  password: !secret wappw
  ap:
    ssid: ${fallbackssid}
    password: !secret hotspotpw  

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

captive_portal:

api:
  password: !secret apipw

# Disable logging over USB
logger:
  baud_rate: 0
  
ota:
  platform: esphome
  password: !secret apipw

binary_sensor:
  - platform: status
    name: "${friendlyname} Status"
  - platform: template
    device_class: power
    name: "${friendlyname} On"
    lambda: |-
      if (id(plug_power).state > 10.0) {
        return true;
      } else {
        return false;
      }

switch:
  - platform: gpio
    internal: true
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_ON

status_led:
  pin:
    inverted: True
    number: GPIO13

substitutions:
  sensor_update_interval: 5s

sensor:
  - platform: wifi_signal
    name: "${friendlyname} WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "${friendlyname} Current"
      filters:
        - throttle_average: ${sensor_update_interval}
    voltage:
      name: "${friendlyname} Voltage"
      filters:
        - throttle_average: ${sensor_update_interval}
    power:
      name: "${friendlyname} Power" 
      id: plug_power
      filters:
        # - multiply: 0.001
        - throttle_average: ${sensor_update_interval}
      unit_of_measurement: W 
  - platform: total_daily_energy
    unit_of_measurement: 'Wh'
    name: "${friendlyname} Consumption"
    power_id: plug_power
    filters:
      - throttle_average: ${sensor_update_interval}
      # - multiply: 1000

time:
  - platform: sntp