esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid  
  password: !secret wappw
  ap:
    ssid: ${fallbackssid}
    password: !secret hotspotpw  

uart:
  rx_pin: RX
  baud_rate: 4800

captive_portal:

api:
  password: !secret apipw

# Disable logging over USB
logger:
  baud_rate: 0
  
ota:
  password: !secret apipw

binary_sensor:
 - platform: status
   name: "${friendlyname} Status"

switch:
  - platform: gpio
    internal: true
    id: relay
    pin: GPIO12
    restore_mode: ALWAYS_ON

button:
  - platform: template
    name: "${friendlyname} Reset"
    on_press:
      then:
        script.execute: reset_timer

status_led:
  pin:
    inverted: True
    number: GPIO13

# sensor:
#   - platform: wifi_signal
#     name: "${friendlyname} WiFi Signal"
#     update_interval: 60s

script:
  - id: reset_timer
    mode: restart
    then: 
      - switch.turn_off: relay
      - delay: 2000ms
      - switch.turn_on: relay
